[package]
name = "drv8323rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0.0"
device-register = "0.4"
modular-bitfield-msb = "0.11"
