[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32G431KB"
rustflags = [
    "-C",
    "linker=flip-link",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"

[alias]
rb = "run --bin firmware"
rbb = "run --release --bin firmware"
bbr = "build --release --bin firmware"
